(package_clause name: (package_identifier) @name) @definition.module
(trait_definition name: (identifier) @name) @definition.trait
(enum_definition name: (identifier) @name) @definition.enum
(simple_enum_case name: (identifier) @name) @definition.enum-case
(full_enum_case name: (identifier) @name) @definition.enum-case
(class_definition name: (identifier) @name) @definition.class
(object_definition name: (identifier) @name) @definition.object
(function_definition name: (identifier) @name) @definition.function
(function_declaration name: (identifier) @name) @definition.function
(val_definition pattern: (identifier) @name) @definition.variable
(given_definition name: (identifier) @name) @definition.variable
(var_definition pattern: (identifier) @name) @definition.variable
(val_declaration name: (identifier) @name) @definition.variable
(var_declaration name: (identifier) @name) @definition.variable
(type_definition name: (type_identifier) @name) @definition.type
(class_parameter name: (identifier) @name) @definition.property
