import type { InitialAtlas } from '../types'

export function KnowledgeView({ atlas }: { atlas: InitialAtlas }) {
  return <main className="knowledge-view" id="atlas-main"><aside className="chapter-rail"><p className="eyebrow">Living textbook</p><h2>How to think about ARC</h2>{['The destination', 'Why a weak model can work', 'Dynamic graph', 'Evidence and authority', 'Context as virtual memory', 'Learning across episodes', 'Complete product journey'].map((title, index) => <a href={`#chapter-${index + 1}`} key={title}><span>{String(index + 1).padStart(2, '0')}</span>{title}</a>)}</aside><article className="reader"><p className="eyebrow">Chapter 1 · north star</p><h1 id="chapter-1">A familiar coding agent, powered by a different kind of intelligence.</h1><p className="reader-lede">The user should still experience one task, useful questions, visible progress, a diff, a verified result, and recovery. The difference lives underneath: the local model proposes; the surrounding organism remembers, structures, checks, recovers, and learns.</p>
    <section id="chapter-2"><h2>Why a weak local model can become a strong system</h2><p>A 9B model has weak priors, limited context, and unreliable self-judgment. ARC does not ask it to become magically smarter. It narrows each decision, supplies the right evidence, makes unsafe actions impossible, and preserves the problem state outside the model.</p><div className="concept-grid">{atlas.journeys.constitutionalKernels.map(kernel => <article key={kernel.id}><span>Kernel</span><h3>{kernel.name}</h3><p>{kernel.summary}</p></article>)}</div></section>
    <section id="chapter-3"><h2>The dynamic graph is the work, not a diagram of the work</h2><p>Nodes are live questions, tasks, evidence requests, branches, attempts, checks, effects, and decisions. New evidence or clarification can invalidate descendants, trigger backtracking, merge branches, or open a new strategy. The graph is closer to a programmable workflow organism than a stored chain of thought.</p></section>
    <section id="chapter-4"><h2>Beliefs predict. Physical evidence authorizes.</h2><p>The model may suggest what is true or what to do next. It cannot certify its own output, claim a write happened, or declare the task complete. Independent receipts, evaluators, repository state, and event authority decide those transitions.</p><ol className="proof-ladder">{atlas.journeys.proofLadder.map((rung, index) => <li key={rung}><span>{index + 1}</span><strong>{rung.replaceAll('-', ' ')}</strong></li>)}</ol></section>
    <section id="chapter-5"><h2>Context is virtual memory, not a growing prompt</h2><p>The durable system keeps the complete semantic address space. A small resident set enters the model. The model may request bounded pages; the runtime proves what was included and omitted, records backtracking, and refuses work when required evidence cannot fit.</p></section>
    <section id="chapter-6"><h2>Learning is slower than acting</h2><p>One episode stays frozen. Only independently reopened evidence from closed tasks may change a future controller, skill, memory, or specialist policy. This blocks same-episode self-promotion and makes rollback possible.</p></section>
    <section id="chapter-7"><h2>The complete journey</h2><p>The destination is not an impressive graph. It is a correctly understood request, an evidence-conditioned strategy, a bounded candidate, a verified detached effect, explicit promotion, reopened user-visible state, and completion only after the final repository is rechecked.</p></section>
  </article><aside className="reader-sidecar"><p className="eyebrow">Failure modes this chapter prevents</p>{atlas.journeys.pitfalls.slice(0, 12).map(pitfall => <article key={pitfall.id}><strong>{(pitfall.name || pitfall.id).replaceAll('-', ' ')}</strong><p>{pitfall.summary}</p></article>)}</aside></main>
}
